name: Run iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Install Maven and Node.js
        run: |
          brew install maven
          brew install node

      - name: Install Appium
        run: npm install -g appium

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Start Appium server
        run: appium &

      - name: Build and run tests
        run: mvn clean test
