name: iOS Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install general dependencies
        run: |
          brew install node
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          gem install xcpretty

      - name: Install Appium
        run: npm install -g appium
        # Install Appium globally

      - name: Verify Appium Installation
        run: appium --version
        # Confirm that Appium was installed successfully

      - name: Install Appium xcuitest driver
        run: sudo appium driver install xcuitest
        # Install the iOS driver

      - name: Verify xcuitest driver installation
        run: appium driver list --installed
        # List installed drivers to confirm xcuitest is installed

      - name: List available simulators
        run: xcrun simctl list devices
        # List all available simulators

      - name: Start and wait for simulator
        run: |
          simulator_name="iPhone 15 Pro" # Ensure this matches the name or UDID from the list

          # Start the simulator
          echo "Starting simulator: $simulator_name"
          xcrun simctl boot "$simulator_name"

          echo "Waiting for simulator to boot..."
          # Loop to wait for the simulator to boot
          for i in {1..30}; do
            boot_status=$(xcrun simctl bootstatus "$simulator_name" 2>&1)
            
            if echo "$boot_status" | grep -q 'Booted'; then
              echo "Simulator booted successfully."
              break
            elif echo "$boot_status" | grep -q 'shutdown'; then
              echo "Simulator is shutting down, trying to boot again."
              xcrun simctl boot "$simulator_name"
            else
              echo "Boot status: $boot_status"
            fi

            echo "Waiting... ($i/30)"
            sleep 15
          done
          
          if [[ "$boot_status" != *"Booted"* ]]; then
            echo "Simulator did not boot successfully."
            exit 1
          fi
        shell: /bin/bash -e {0}
        env:
          JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/19.0.2-7/x64/Contents/Home

      - name: Start Appium server
        run: appium --log-level debug &
        continue-on-error: true

      - name: Run Appium tests
        run: mvn clean test
