name: iOS Tests

on: [push]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Appium
      run: npm install -g appium

    - name: Install XCUITest Driver
      run: npm install -g appium-xcuitest-driver

    - name: Boot iOS Simulator
      id: boot_simulator
      run: |
        # Find UDID of the iPhone 15 Pro simulator
        SIMULATOR_UDID=$(xcrun simctl list devices | grep 'iPhone 15 Pro' | grep 'Shutdown' | head -n 1 | awk -F'(' '{print $2}' | awk -F')' '{print $1}')
        if [ -z "$SIMULATOR_UDID" ]; then
          echo "No available simulator found."
          exit 1
        fi
        echo "Booting simulator with UDID: $SIMULATOR_UDID"
        xcrun simctl boot $SIMULATOR_UDID
        # Wait for the simulator to boot
        xcrun simctl bootstatus $SIMULATOR_UDID --timeout 600
        # Install the app
        xcrun simctl install $SIMULATOR_UDID apps/UIKitCatalog.app

    - name: Start Appium Server
      run: appium &

    - name: Run Tests
      run: |
        # Replace with your test command
        npm test

    - name: Cleanup
      if: always()
      run: |
        # Shutdown the simulator
        SIMULATOR_UDID=$(xcrun simctl list devices | grep 'iPhone 15 Pro' | grep 'Shutdown' | head -n 1 | awk -F'(' '{print $2}' | awk -F')' '{print $1}')
        if [ ! -z "$SIMULATOR_UDID" ]; then
          xcrun simctl shutdown $SIMULATOR_UDID
        fi
