name: Run iOS UI Tests

on:
  push:
    branches:
      - main

jobs:
  ios-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'

    - name: Install Appium
      run: sudo npm install -g appium

    - name: Install or Update XCUItest Driver
      run: sudo appium driver install xcuitest

    - name: Start Appium Server
      run: |
        nohup appium --use-plugins xcuitest &
        sleep 20 # Allow some time for Appium to start

    - name: Wait for Appium Server
      run: |
        until curl -s http://localhost:4723/wd/hub/status | grep '"status": 0'; do
          echo "Waiting for Appium server..."
          sleep 5
        done

    - name: Install and Configure iOS Simulator
      run: |
        xcrun simctl boot "iPhone 15 Pro (2nd generation)"
        xcrun simctl install booted apps/UIKitCatalog.app

    - name: Run iOS UI tests
      env:
        APPIUM_SERVER_URL: http://localhost:4723/wd/hub
      run: mvn test

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/
