name: iOS Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'  # Use 'temurin' for the Eclipse Temurin JDK distribution

      - name: Install dependencies
        run: |
          brew install node
          npm install -g appium
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          gem install xcpretty

      - name: Start Appium server
        run: appium &
        continue-on-error: true

      - name: Run Appium tests
        run: mvn clean test
