name: iOS Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install general dependencies
        run: |
          brew install node
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          gem install xcpretty

      - name: Install Appium and drivers
        run: |
          npm install -g appium
          npm install -g appium-xcuitest-driver # Install the iOS driver

      - name: Verify xcuitest driver installation
        run: appium driver list --installed
        # This command will list all installed drivers, including xcuitest

      - name: Start Appium server
        run: appium --log-level debug &
        continue-on-error: true

      - name: Run Appium tests
        run: mvn clean test
