name: iOS Appium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install general dependencies
        run: |
          brew install node
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          gem install xcpretty

      - name: Install Appium
        run: npm install -g appium

      - name: Verify Appium Installation
        run: appium --version

      - name: Install Appium xcuitest driver
        run: sudo appium driver install xcuitest

      - name: Verify xcuitest driver installation
        run: appium driver list --installed

      - name: Stop all simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Start specific simulator
        run: |
          xcrun simctl boot "iPhone 15 Pro" # Replace with your simulator name or UDID
          sleep 60 # Increase sleep time if necessary

      - name: Start Appium server
        run: |
          appium --log-level debug &
          sleep 15 # Wait for Appium server to start

      - name: Run Appium tests
        run: mvn clean test
